import Head from 'next/head'
import React, {useState} from 'react'
import style from '../styles/Home.module.css'
import Link from 'next/link'
import ClipLoader from "react-spinners/ClipLoader"
import Navbar from '../component/Navbar'
export default function Home() {
  const [email, setEmail] = useState()

  async function handler(e){
    e.preventDefault();

    const blogs = {email}

    const response = await fetch ("https://beautybytas.onrender.com/signin",{
      method:"POST",
      headers: {"Content-Type": "application/json"},
      body: JSON.stringify(blogs)
    })
    const data = await response.json();
    console.log(data)
  }
  return (
    <div className={style.container}>
      <div className={style.overlay}>
        <Head>
          <title>Hauskino</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
            <Navbar/>

           <div className={style.main}>
                <h1>Unlimited films,TV</h1>
                <h1>Programmes and more.</h1>
                <p>watch anywhere, Cancel at any time.</p>
                  <div className={style.try}>
                   <form onSubmit={handler}>
                    <input
                    value={email}
                     onChange={(e)=> setEmail(e.target.value)}
                     type="text"/>
                     
                    <button type='submit'>TRY IT NOW </button>
                    </form> 
                    </div>
                    <p>Ready to watch ? Enter your email to create your membership</p>
           </div>

         </div>
    </div>
  )
}
