import Head from 'next/head'
import React, {useState} from 'react'
import style from '../styles/Home.module.css'
import Link from 'next/link'
import ClipLoader from "react-spinners/ClipLoader"
import Navbar from '../component/Navbar'
export default function Home() {
  const [email, setEmail] = useState()
  const [loading, setLoading] = useState()
  // const [data , setData] = useState()

 async function handler(e){
    e.preventDefault();
    setLoading(true)
      const response =  await fetch ("https://beautybytas.onrender.com/signup", {
        method:"POST",
        headers: {"Content-Type": "application/json"},
        body: JSON.stringify({email})
      })
      const server = await response.json();
      setLoading(false)
      console.log(server)
      // setData(data.msg)
  }
  return (
    <div>
      <Head>
        <title>Hauskino</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          
          <div className={style.container}>
            <div className={style.overlay}>
                <Navbar/>

              <div className='text-white flex flex-col gap-2 justify-center p-10 items-center'>
                <h1 className='text-6xl font-bold'>Unlimited movies, TV</h1>
                <h1 className='text-5xl font-bold'>shows, and more.</h1>
                <p className='text-3xl'>Watch anywhere. cancel anytime.</p>
                <p className='text-3xl'>Ready to Watch? Enter your email to create or retart your membership.</p>
              </div>

          <div className='text-white p-10 flex  justify-center'>
            <form onSubmit={handler} className='flex gap-5 flex-col'>
              <input 
               value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder='Email address:'
              className='p-4 w-80 text-xl text-black outline-none'
               type='text'/>
              <button className='bg-red-700 p-4 text-xl' type='submit'>{loading ? <ClipLoader color={"red"} loading={loading}  size={50}/>:"Get Started"}</button>
              
              {/* {data && data.msg} */}
            </form>
    </div>


            </div>
          </div>
    </div>
  )
}
